### ISSUE TITLE
can't get any stock info

### ISSUE THREAD

**Issue by lshvarzberg** [thess/MMM-MktIndex#4]
This module had worked for some time but several weeks ago I have stopped receiving any stock data.
Now all I get is empty table
I have reinstalled the module but this did not change anything. Still no data 

Here is what I see when I run manually npm start:

[2024-06-10 19:53:48.117] [ERROR] [MKTINDEX] API Error: request to https://finance.yahoo.com/quote/AAPL failed, reason:

The message cuts at “reason” so not much help there …

Any ideas what could go wrong?

**Comment by thess** [comment]
Yahoo finance site changed some re-direction locations. Fixed by: 03ce9f95731bd80c0f0f26e94768307fa1d0052c

Upgrade yahoo-finance2 to v2.13,3

**Comment by lshvarzberg** [comment]
I have already upgraded to the latest rev a couple of days ago, but the
problem persists ......

{
  "name": "MMM-MktIndex",
  "version": "1.3.2",
  "description": "MagicMirror Module for displaying market indexes from
Yahoo Finance",
  "main": "MMM-MktIndex.js",

..........................

  },
  "dependencies": {
    "yahoo-finance2": "^2.11.3"
  },
  "devDependencies": {}
}

**Comment by thess** [comment]
After updating from the repo in MMM-MktIndex, did you execute:
`$ npm install`

You can check what's currently installed with:
`$ npm ls`

**Comment by lshvarzberg** [comment]
Yes, I did npm install, but this did not fix my problem.
I started looking for solutions and workarounds online and somehow stumbled
into a page where they suggested the following command:

 npm i ***@***.***

I tried it and the module started working!

So now it works, hopefully for a while!

Thank you,
Leo

**Comment by hajog68** [comment]
Hello, 
I have the same issue, as described above. 
The solution is not clear to me. What does npm i ***@***.*** mean as fix ?
Is it possible to provide more info about the solution ?
Thanks in advance
Cheers
H.

**Comment by thess** [comment]
Upgrade as follows:

```
cd MagicMirror/modules/MMM-MktIndex
git pull
npm install
```
Works for me. I have no idea what `***@***.***` means - I'm not all that well versed in `npm` subtleties.

**Comment by hajog68** [comment]
Thanks a lot !CheersH.
    Am Mittwoch, 4. September 2024 um 20:43:35 MESZ hat Ted Hess ***@***.***> Folgendes geschrieben:   

 


Upgrade as follows:
cd MagicMirror/modules/MMM-MktIndex
git pull
npm install

Works for me. I have no idea what ***@***.*** means - I'm not all that well versed in npm subtleties.

**Comment by hajog68** [comment]
Hi Ted,

The module still does not work anymore (and I loved this market overview!)

I have done all the upgrades, updates, and the git pull + npm install. 
I also completely deleted the MktIndex folder in the module folder and in the config file. Reinstalled - same result: nothing shows up.
I also checked the files about the yahoo version 1.3.2 and 2.11.3 - all as it should be.

I use the Raspberry Pi 5, may this can be a reason, as it worked always fine on my previous one 4B ?
Any idea ?

Cheers
Hans

**Comment by thess** [comment]
I can't say why this no longer works for you. It may very well have to do with software versions that have been upgraded on your move to the RPi5. Without some additional information from log/console output messages it is impossible for me to see your problem. My current system runs just fine with the version you mention (1.3.2) on Debian 12 and node.js 18.13.0

There are newer versions of node-yahoo-finance2 which I haven't tried at all and quite possibly you have a newer version of node.js and/or its dependencies that may be the issue -- more info needed AND please open a new issue when you do.

**Comment by hajog68** [comment]
Hi Ted,
thanks. 
Okay, lets try to figure out the root cause of the issue.
I will open (as requested) a new issue 

@ Others with RBi5: Does it work on your machine ?
